@host=http://127.0.0.1:8000/api/v1/priorities
###
GET /
###

POST /
Content-Type:application/json
{"name":"Mediacore"}
###

PATCH /3/
Content-Type:application/json
{"name":"High"}
###

DELETE /4868ac66-828f-4260-83cc-8a907c7bccf8/
Authorization: "Bearer JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3NzkwNzEzLCJpYXQiOjE3Mjc3OTA0MTMsImp0aSI6IjMxYmI2NjcxOWRmOTQyYjg5NGM0YTZiNWUwMTQ1NDU0IiwidXNlcl9pZCI6IjcyMTRlNjYwLTdkMDgtNDQ4ZC1hOTBhLWYwYzExNzc3ZGQzNiJ9.5MdnZ6N2qFyF7911qm7In-CSkJzHhUfmWo7XzdU3lBU"
###