# Generated by Django 5.1.1 on 2024-09-15 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
