# Generated by Django 5.1.1 on 2024-09-21 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.CharField(default=datetime.datetime(2024, 9, 21, 10, 24, 50, 950182, tzinfo=datetime.timezone.utc), max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
