@host=http://127.0.0.1:8000/api/v1/auth
###
POST /users/
Content-Type:application/json
{"email":"p.zonuoz@gmail.com","password":"Arman1399@"}
###
POST /jwt/create/
Content-Type:application/json
{"email":"p.zonuoz@gmail.com","password":"Arman1399@"}
###
DELETE /2/