# Generated by Django 5.1.1 on 2024-09-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
